### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by utkarsh2102** [tj/growl#10]
Hi,

There are test failures as follows: 
```
┌──────────────────────────────────────────────────────────────────────────────┐
│ Run tests for ruby2.7 from debian/ruby-tests.rake                            │
└──────────────────────────────────────────────────────────────────────────────┘

RUBYLIB=. GEM_PATH=/home/utkarsh/check/ruby-growl/debian/ruby-growl/usr/share/rubygems-integration/all:/home/utkarsh/.gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0 ruby2.7 -S rake -f debian/ruby-tests.rake
/usr/bin/ruby2.7 -I/usr/share/rubygems-integration/all/gems/rspec-support-3.9.2/lib:/usr/share/rubygems-integration/all/gems/rspec-core-3.9.1/lib /usr/share/rubygems-integration/all/gems/rspec-core-3.9.1/exe/rspec --pattern ./spec/\*\*/\*_spec.rb --format documentation

Growl
  #installed?
    should check if growlnotify is available (FAILED - 1)
  #version
    should return only the version triple (FAILED - 2)
  #notify
    should accept a block, running immediately after (FAILED - 3)
    should accept a hash (FAILED - 4)
    should return nil when not installed (FAILED - 5)
  #notify_ok
    should display ok notifications (FAILED - 6)
  #notify_info
    should display info notifications (FAILED - 7)
  #notify_warning
    should display warning notifications (FAILED - 8)
  #notify_error
    should display error notifications (FAILED - 9)
  #run
    should fail when no message is present (FAILED - 10)
    should execute a growl notification (FAILED - 11)
  #sticky!
    should make a notification stick until explicitly closed (FAILED - 12)
  #name
    should set the application name (FAILED - 13)
  #title
    should add a title (FAILED - 14)
  #appIcon
    should use an application for the icon (FAILED - 15)
  #iconpath
    should use a path for the icon (FAILED - 16)
  #icon
    should use an icon based on a file type (FAILED - 17)
    should allow symbols (FAILED - 18)
  #image
    should use an image path for the 'icon' (FAILED - 19)

Failures:

  1) Growl#installed? should check if growlnotify is available
     Failure/Error: @growl.message = 'Hello World'
     
     NoMethodError:
       undefined method `message=' for nil:NilClass
     # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  2) Growl#version should return only the version triple
     Failure/Error: @growl.message = 'Hello World'
     
     NoMethodError:
       undefined method `message=' for nil:NilClass
     # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  3) Growl#notify should accept a block, running immediately after
     Failure/Error: @growl.message = 'Hello World'
     
     NoMethodError:
       undefined method `message=' for nil:NilClass
     # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  4) Growl#notify should accept a hash
     Failure/Error: @growl.message = 'Hello World'
     
     NoMethodError:
       undefined method `message=' for nil:NilClass
     # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  5) Growl#notify should return nil when not installed
     Failure/Error: @growl.message = 'Hello World'
     
     NoMethodError:
       undefined method `message=' for nil:NilClass
     # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  6) Growl#notify_ok should display ok notifications
     Failure/Error: @growl.message = 'Hello World'
     
     NoMethodError:
       undefined method `message=' for nil:NilClass
     # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  7) Growl#notify_info should display info notifications
     Failure/Error: @growl.message = 'Hello World'
     
     NoMethodError:
       undefined method `message=' for nil:NilClass
     # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  8) Growl#notify_warning should display warning notifications
     Failure/Error: @growl.message = 'Hello World'
     
     NoMethodError:
       undefined method `message=' for nil:NilClass
     # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  9) Growl#notify_error should display error notifications
     Failure/Error: @growl.message = 'Hello World'
     
     NoMethodError:
       undefined method `message=' for nil:NilClass
     # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  10) Growl#run should fail when no message is present
      Failure/Error: @growl.message = 'Hello World'
      
      NoMethodError:
        undefined method `message=' for nil:NilClass
      # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  11) Growl#run should execute a growl notification
      Failure/Error: @growl.message = 'Hello World'
      
      NoMethodError:
        undefined method `message=' for nil:NilClass
      # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  12) Growl#sticky! should make a notification stick until explicitly closed
      Failure/Error: @growl.message = 'Hello World'
      
      NoMethodError:
        undefined method `message=' for nil:NilClass
      # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  13) Growl#name should set the application name
      Failure/Error: @growl.message = 'Hello World'
      
      NoMethodError:
        undefined method `message=' for nil:NilClass
      # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  14) Growl#title should add a title
      Failure/Error: @growl.message = 'Hello World'
      
      NoMethodError:
        undefined method `message=' for nil:NilClass
      # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  15) Growl#appIcon should use an application for the icon
      Failure/Error: @growl.message = 'Hello World'
      
      NoMethodError:
        undefined method `message=' for nil:NilClass
      # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  16) Growl#iconpath should use a path for the icon
      Failure/Error: @growl.message = 'Hello World'
      
      NoMethodError:
        undefined method `message=' for nil:NilClass
      # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  17) Growl#icon should use an icon based on a file type
      Failure/Error: @growl.message = 'Hello World'
      
      NoMethodError:
        undefined method `message=' for nil:NilClass
      # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  18) Growl#icon should allow symbols
      Failure/Error: @growl.message = 'Hello World'
      
      NoMethodError:
        undefined method `message=' for nil:NilClass
      # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

  19) Growl#image should use an image path for the 'icon'
      Failure/Error: @growl.message = 'Hello World'
      
      NoMethodError:
        undefined method `message=' for nil:NilClass
      # ./spec/growl_spec.rb:18:in `block (2 levels) in <top (required)>'

Finished in 0.00537 seconds (files took 0.09404 seconds to load)
19 examples, 19 failures

Failed examples:

rspec ./spec/growl_spec.rb:5 # Growl#installed? should check if growlnotify is available
rspec ./spec/growl_spec.rb:11 # Growl#version should return only the version triple
rspec ./spec/growl_spec.rb:22 # Growl#notify should accept a block, running immediately after
rspec ./spec/growl_spec.rb:26 # Growl#notify should accept a hash
rspec ./spec/growl_spec.rb:30 # Growl#notify should return nil when not installed
rspec './spec/growl_spec.rb[1:4:1]' # Growl#notify_ok should display ok notifications
rspec './spec/growl_spec.rb[1:5:1]' # Growl#notify_info should display info notifications
rspec './spec/growl_spec.rb[1:6:1]' # Growl#notify_warning should display warning notifications
rspec './spec/growl_spec.rb[1:7:1]' # Growl#notify_error should display error notifications
rspec ./spec/growl_spec.rb:46 # Growl#run should fail when no message is present
rspec ./spec/growl_spec.rb:50 # Growl#run should execute a growl notification
rspec ./spec/growl_spec.rb:56 # Growl#sticky! should make a notification stick until explicitly closed
rspec ./spec/growl_spec.rb:67 # Growl#name should set the application name
rspec ./spec/growl_spec.rb:74 # Growl#title should add a title
rspec ./spec/growl_spec.rb:82 # Growl#appIcon should use an application for the icon
rspec ./spec/growl_spec.rb:90 # Growl#iconpath should use a path for the icon
rspec ./spec/growl_spec.rb:98 # Growl#icon should use an icon based on a file type
rspec ./spec/growl_spec.rb:104 # Growl#icon should allow symbols
rspec ./spec/growl_spec.rb:112 # Growl#image should use an image path for the 'icon'
```

However, I am using this patch:
```
--- a/spec/growl_spec.rb
+++ b/spec/growl_spec.rb
@@ -1,4 +1,4 @@
-
+require 'growl'
 describe Growl do
   
   describe "#installed?" do
@@ -116,4 +116,4 @@
     end
   end
   
-end
\ No newline at end of file
+end
```

Otherwise, I get:
```
An error occurred while loading ./spec/growl_spec.rb.
Failure/Error:
  describe Growl do
    
    describe "#installed?" do
      it "should check if growlnotify is available" do
        Growl.should be_installed
      end
    end
    
    describe "#version" do
      it "should return only the version triple" do

NameError:
  uninitialized constant Growl
# ./spec/growl_spec.rb:2:in `<top (required)>'
No examples found.

Finished in 0.00005 seconds (files took 0.16467 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by lukaszkorecki** [comment]
Hi @utkarsh2102 - given that nobody contributed to this project in over 5 years, I very much doubt it still works. Further more, macOS ships with it's own notification system now, which can be invoked via shell:

```
osascript -e 'display notification "Whatsup?"'
````

I don't think it would be wise use of time to fix this - I'm going to go ahead and close your issue.

Also, I'll most likely archive this repository as Growl itself seems to be unmaintained cc  @tj
